import { memo } from "react";
import ButtonDesign from "./button";
import CheckboxDesign from "./checkbox";
import DrawerDesign from "./drawer";
import FileUploadDesign from "./fileupload";
import InputDesign from "./input";
import LoadingContainerDesign from "./loadingcontainer";
import ModalDesign from "./modal";
import RadioDesign from "./radio";
import SwitchDesign from "./switch";
import TextAreaDesign from "./textarea";
import DividerDesign from "./divider";

export const Button = ButtonDesign;
export const Checkbox = CheckboxDesign;
export const Drawer = DrawerDesign;
export const FileUpload = FileUploadDesign;
export const Input = InputDesign;
export const LoadingContainer = LoadingContainerDesign;
export const Modal = ModalDesign;
export const Radio = RadioDesign;
export const Switch = SwitchDesign;
export const TextArea = TextAreaDesign;
export const Divider = DividerDesign;
